services:
  java-app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile.dev
    working_dir: /workspaces/J17P16-03
    volumes:
      - .:/workspaces/J17P16-03:cached
      # ユーザーがrootに戻ったため、パスを修正
      - maven-cache:/root/.m2
    depends_on:
      postgres-db: { condition: service_healthy }
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    # JAVA_TOOL_OPTIONSは削除
    ports:
      - "5005:5005"
    # user: vscode は削除
    command: tail -f /dev/null

  postgres-db:
    image: postgres:16
    restart: always
    # ▼▼▼ commandセクションを追記 ▼▼▼
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      # ▼▼▼ postgresql.confのマウントを追記 ▼▼▼
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "${HOST_PGADMIN_PORT}:80"
    depends_on:
      postgres-db: { condition: service_healthy }

volumes:
  pgdata:
  maven-cache:
